language: go
go:
  - '1.11'

install:
  - go get github.com/gohugoio/hugo
  - npm install -g markdownlint-cli
  - echo $KNOWN_HOSTS_KEY >> $HOME/.ssh/known_hosts

script:
  - markdownlint content/*.md
  - markdownlint content/post/*.md
  - hugo
