matrix:
  include:
    - language: node_js
      node_js: 10.15
      install:
        - npm install -g markdownlint-cli
        - echo $KNOWN_HOSTS_KEY >> $HOME/.ssh/known_hosts
      script:
        - markdownlint content/*.md
        - markdownlint content/post/*.md
    - language: go
      go: '1.11'
      install:
        - go get github.com/gohugoio/hugo
      script:
        - hugo
    - language: python
      python: 3.6
      install:
        - pip install -r requirements.txt
      script:
        - ./articles queue
