env:
  - hugo_version=0.56.3

jobs:
  include:
    - language: node_js
      stage: test
      node_js: 10.15
      install:
        - npm install -g markdownlint-cli
      script:
        - markdownlint content/*.md
        - markdownlint content/post/*.md
    - language: python
      stage: test
      python: 3.7
      env:
        - EDITOR=/usr/bin/vim
        - hugo_version=0.56.3
      install:
        - pip install -r requirements.txt
      script:
        - ./articles queue
    - language: go
      stage: test
      go: '1.11'
      install:
        - wget https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/hugo_${hugo_version}_Linux-64bit.tar.gz -O hugo.tar.gz
        - tar xvfz hugo.tar.gz
        - ./hugo version
      script:
        - ./hugo --buildFuture
    - language: python
      python: 3.7
      stage: deploy
      env:
        - hugo_version=0.56.3
        - EDITOR=/usr/bin/vim
      install:
        - wget https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/hugo_${hugo_version}_Linux-64bit.tar.gz -O hugo.tar.gz
        - tar xvfz hugo.tar.gz
        - ./hugo version
        - pip install -r requirements.txt
      script:
        - ./hugo --buildFuture
      before_deploy:
        - echo $KNOWN_HOSTS_KEY >> $HOME/.ssh/known_hosts
        - openssl aes-256-cbc -K $encrypted_e2fa1c035576_key -iv $encrypted_e2fa1c035576_iv -in deploy_rsa.enc -out deploy_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 deploy_rsa
        - ssh-add deploy_rsa
        - wget -O /tmp/index.xml https://entbehrlich.es/index.xml
      deploy:
        - provider: script
          skip_cleanup: true
          script: rsync -avi --delete public/ $DEPLOY_TARGET
          on:
            branch: master
      after_deploy:
        - ./articles tweet -n https://entbehrlich.es/index.xml -o /tmp/index.xml
