language: generic
go:
  - '1.11'
python:
  - "3.6"

install:
  - go get github.com/gohugoio/hugo
  - npm install -g markdownlint-cli
  - echo $KNOWN_HOSTS_KEY >> $HOME/.ssh/known_hosts
  - pip install -r requirements.txt

script:
  - markdownlint content/*.md
  - markdownlint content/post/*.md
  - hugo
  - ./articles queue
