name: Deploy
on:
  push:
    branches:
    - master

jobs:
  deploy_job:
    name: Deploy Job
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Hugo build
      env:
        EDITOR: /usr/bin/vim
      run: |
        sudo snap install hugo --channel=extended
        hugo --buildFuture
    - name: SSH setup
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
      run: |
        mkdir -p ~/.ssh
        echo "${KNOWN_HOSTS}" >> ~/.ssh/known_hosts
        echo "${DEPLOY_KEY}" > ~/.ssh/my_rsync_key
        echo "IdentityFile ~/.ssh/my_rsync_key" >> ~/.ssh/config
        chmod -R 700 ~/.ssh
    - name: Copy old feed for reference in Social
      run: |
        sudo apt install -y wget 
        wget -O /tmp/index.xml https://entbehrlich.es/index.xml
    - name: Rsync deployment
      env:
        RSYNC_USER: ${{ secrets.RSYNC_USER }}
        HOST: ${{ secrets.HOST }}
      run: |
        rsync -avz -e ssh --delete public/ ${RSYNC_USER}@${HOST}:public/    
    - name: Social posts
      env:
        EDITOR: /usr/bin/vi
        tw_access_token: ${{ secrets.TW_ACCESS_TOKEN}}
        tw_access_token_secret: ${{ secrets.TW_ACCESS_TOKEN_SECRET}}
        tw_con_key: ${{ secrets.TW_CON_KEY}}
        tw_con_secret: ${{ secrets.TW_CON_SECRET}}
        entbehrliches_bot_token: ${{ secrets.ENTBEHRLICHES_BOT_TOKEN }}
        entbehrliches_telegram_chat_id: ${{ secrets.ENTBEHRLICHES_TELEGRAM_CHAT_ID }}
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        ./articles tweet -n https://entbehrlich.es/index.xml -o /tmp/index.xml
        ./articles telegram -n https://entbehrlich.es/index.xml -o /tmp/index.xml
