# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Release a new post

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          token: ${{ secrets.PAT }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Release a new Post
      env:
        EDITOR: /usr/bin/vi 
      run: |
        git config --global user.name 'Botty McBotface'
        git config --global user.email 'noqqe@users.noreply.github.com'
        ./articles release
